GET https://api.github.com/users/johnmarksinclair/repos
// returns all repos for a specified user
###
GET https://api.github.com/repos/microsoft/Git-Credential-Manager-Core/languages
// returns the languages used in a specified repo
###
GET https://api.github.com/users/johnmarksinclair
// returns user info

// http://localhost:3000/ - also works with rest client