GET https://api.github.com/users/johnmarksinclair/repos
// returns all repos for a specified user
###
GET https://api.github.com/users/johnmarksinclair/followers
// returns list of users followers
###
GET https://api.github.com/repos/johnmarksinclair/college
###
###
###
###
GET https://api.github.com/repos/johnmarksinclair/college/languages
// returns the languages used in a specified repo
###
GET https://api.github.com/users/johnmarksinclair
// returns user info

// http://localhost:3000/ - also works with rest client